### ISSUE TITLE
Many missing materials

### ISSUE THREAD

**Issue by gpvillamil** [Unity-Technologies/animation-rigging-workshop-siggraph2019#1]
I'm having a hard time getting started with this project. I fixed some errors due to an outdated version of the LWRP, and now the project loads and the game starts, but there appear to be a lot of missing materials.

I'm on the 2019.3 beta and LWRP is at 7.01 - anything else I should try?

<img width="1552" alt="Screen Shot 2019-08-31 at 7 16 35 AM" src="https://user-images.githubusercontent.com/342238/64065206-7003cc80-cbbf-11e9-8ebe-d7a8b65770a7.png">

**Comment by gpvillamil** [comment]
Here's my editor log:
[Editor.log](https://github.com/Unity-Technologies/animation-rigging-workshop-siggraph2019/files/3562530/Editor.log)

**Comment by gpvillamil** [comment]
It seems like the materials are there, just not rendering properly. When I select a material it previews correctly in the inspector, and the associated textures all seem to be there.

<img width="1552" alt="Screen Shot 2019-08-31 at 7 32 27 AM" src="https://user-images.githubusercontent.com/342238/64065370-b0644a00-cbc1-11e9-9002-1ddcb5f5d0b2.png">

<img width="1552" alt="Screen Shot 2019-08-31 at 7 32 44 AM" src="https://user-images.githubusercontent.com/342238/64065371-b65a2b00-cbc1-11e9-8ff8-62db40d3ccf9.png">

**Comment by gpvillamil** [comment]
Going to the missing materials and switching them to another shader type (eg Autodesk) and then back seems to get them to work.

Something seems up with the LOD mechanism, some LOD materials appear to be still missing after doing that.

And now the project won't run, throws a bunch of compiler errors :(
<img width="1552" alt="Screen Shot 2019-09-02 at 8 04 15 AM" src="https://user-images.githubusercontent.com/342238/64123219-9c068580-cd58-11e9-9e36-e0a4534127e0.png">
<img width="1552" alt="Screen Shot 2019-09-02 at 8 04 10 AM" src="https://user-images.githubusercontent.com/342238/64123221-9c068580-cd58-11e9-948d-ad067c3bb6de.png">

**Comment by davehunt-unity** [comment]
Hi gpvillamil thanks for your issue report. Really sorry to hear you have experienced difficulties. I have a solution for you, and I'll also explain a bit more about what's going on here for reference.

You are correct, this project was built using Unity 2019.2. The upgrade to Unity 2019.3 includes the switch from LWRP to Universal RP and this upgrade is intended to be seamless and automatic. However, you have helped us discover a bug in the upgrade process, thank you! The issue has now been reported to the Universal RP team and they will be sure to fix it for future versions. 

In the meantime, you can follow these steps to work around the issue and get the project upgraded to 2019.3b1. 
1. Do a fresh clone of the project repository from github
2. Edit the project manifest to point to LWRP version 7.0.1
This is in Packages/manifest.json. Edit the LWRP line to say: 
"com.unity.render-pipelines.lightweight": "7.0.1",
3. Open the project in Unity 2019.3b1

I tried this on my machine just now and verified that it works. Let us know if you run into any problems. Again, thank you very much for letting us know about this issue because it will help us prevent others from having the same problem.

If you would like to take the additional step to report this issue as an official bug in Unity you have the chance to win a new graphics card! Here is the link to more information on that if you are interested.
https://blogs.unity3d.com/2019/08/27/unity-2019-3-beta-is-now-available/

**Comment by gpvillamil** [comment]
Thanks! I'll try that!

Also submitted the bug report.

**Comment by gpvillamil** [comment]
That worked perfectly, on Windows 10 and Mac OS. Thanks!
